//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int oid { get; set; }
        public int bid { get; set; }
        public System.DateTime sdate { get; set; }
        public System.DateTime edate { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
